SELECT stu_id FROM STUDENT s, DEPARTMENT d
WHERE s.DEPT_ID = d.DEPT_ID AND dept_name = '산업공학과'
MINUS 
SELECT stu_id FROM TAKES
WHERE grade = 'A+';

SELECT title, credit, YEAR, semester
FROM COURSE, CLASS
WHERE course.COURSE_ID = class.COURSE_ID; 

SELECT title, credit, YEAR, semester
FROM COURSE LEFT OUTER JOIN CLASS
USING(COURSE_id);

SELECT title, credit, YEAR, semester
FROM COURSE, CLASS
WHERE course.COURSE_ID = class.COURSE_ID(+);

SELECT title, credit, YEAR, semester
FROM COURSE, CLASS
WHERE course.COURSE_ID(+) = class.COURSE_ID;

SELECT title, credit, YEAR, semester
FROM COURSE RIGHT OUTER JOIN CLASS
USING (COURSE_id);

SELECT title, credit, YEAR, semester
FROM COURSE FULL OUTER JOIN CLASS
USING (COURSE_id);

SELECT * FROM EMP;

SELECT *
FROM EMP
ORDER BY 6 DESC, 1;

SELECT COUNT(*)
FROM STUDENT
WHERE YEAR = 3;
SELECT * FROM STUDENT;

SELECT * FROM emp;

SELECT COUNT(COMM)
FROM EMP;

SELECT count(DISTINCT dept_id)
FROM STUDENT;

SELECT * FROM STUDENT;

SELECT COUNT(*)
FROM STUDENT s, DEPARTMENT d
WHERE s.DEPT_ID = d.DEPT_ID AND d.DEPT_NAME = '컴퓨터공학과';

SELECT count(*)
FROM EMP e
WHERE e.JOB = 'SALESMAN';

SELECT COUNT(*)
FROM EMP e
WHERE e.JOB = 'SALESMAN' AND e.SAL >= 1500;

SELECT * FROM EMP
WHERE emp.JOB = 'SALESMAN';

SELECT sum(2012-year_emp)
FROM PROFESSOR;

SELECT 2012 - YEAR_EMP
FROM PROFESSOR p;

SELECT SUM(sal)
FROM EMP e
WHERE e.JOB = 'SALESMAN';

SELECT DISTINCT  JOB 
FROM EMP;

SELECT * FROM DEPT;

SELECT SUM(SAL)  
FROM DEPT, EMP
WHERE DEPT.DEPTNO = EMP.DEPTNO AND DNAME = 'RESEARCH';

SELECT avg(2012 - year_emp)
FROM PROFESSOR;

SELECT avg(sal)
FROM EMP e
WHERE e.JOB = 'CLERK';  --1037.5

SELECT avg(sal)
FROM EMP e
WHERE e.JOB = 'SALESMAN';    --1400

SELECT avg(sal)
FROM EMP e
WHERE e.JOB = 'MANAGER';    --2758.33333..

SELECT avg(sal)
FROM EMP e
WHERE e.JOB = 'ANALYST';    --3000

SELECT avg(sal)
FROM EMP e
WHERE e.JOB = 'PRESIDENT';   --5000

SELECT max(sal), AVG(sal), MIN(sal)  
FROM EMP e, DEPT d
WHERE e.DEPTNO = d.deptno AND d.DNAME = 'ACCOUNTING';

SELECT *
FROM EMP e, DEPT d
WHERE e.DEPTNO = d.deptno AND d.DNAME = 'ACCOUNTING';

SELECT dept_id, COUNT(*)
FROM STUDENT
GROUP BY dept_id;

SELECT * FROM STUDENT;

SELECT dept_name, COUNT(*)
FROM STUDENT s, DEPARTMENT d
WHERE s.DEPT_ID = d.DEPT_ID 
GROUP BY dept_name;

SELECT dname, COUNT(*), AVG(sal), MAX(sal), MIN(sal)
FROM EMP e, DEPT d 
WHERE e.DEPTNO = d.DEPTNO 
GROUP BY dname
ORDER BY dname;

SELECT dept_name, COUNT(*), AVG(2012 - year_emp) 평균재직년수, MAX(2012 - year_emp) 최대재직년수 
FROM PROFESSOR p, DEPARTMENT d 
WHERE p.DEPT_ID = d.DEPT_ID
GROUP BY dept_name
ORDER BY 평균재직년수;

SELECT * FROM PROFESSOR;

SELECT dept_name, COUNT(*) 교수수, AVG(2012 - year_emp) 평균재직연수, MAX(2012 - year_emp) 최대재직연수
FROM PROFESSOR p, DEPARTMENT d
WHERE p.DEPT_ID = d.DEPT_ID
GROUP BY dept_name
HAVING AVG(2012 - year_emp) >= 10;

SELECT dname, COUNT(*), AVG(sal), MAX(sal), MIN(sal)
FROM EMP e, DEPT d
WHERE e.DEPTNO = d.DEPTNO 
GROUP BY dname
HAVING COUNT(*) >= 5; 

SELECT * FROM EMP
WHERE comm IS NOT NULL;

SELECT stu_id
FROM TAKES
WHERE grade = 'A+';

SELECT *
FROM EMP e
WHERE comm != 1400;

SELECT *
FROM CLASS
WHERE classroom = '301호';

SELECT title
FROM COURSE
WHERE course_id IN 
	(SELECT DISTINCT course_id
	FROM CLASS
	WHERE classroom = '301호');

SELECT DISTINCT title
FROM COURSE c1, CLASS c2
WHERE c1.COURSE_ID = c2.COURSE_ID AND classroom = '301호';

SELECT title
FROM COURSE
WHERE course_id NOT IN ( 
	SELECT DISTINCT course_id
	FROM CLASS
	WHERE YEAR = 2012 AND semester = 2
);

CREATE OR REPLACE VIEW v_takes AS
SELECT stu_id, class_id
FROM TAKES;

SELECT * FROM V_TAKES;
SELECT * FROM TAKES;
	